### ISSUE TITLE
How to use/install the new PSE Get?

### ISSUE THREAD

**Issue by arnemenzo** [yeahbah/NewPSEGet#1]
Hi Sir,

First of all, thank you for your continuous support in developing this program. Really helpful sa mga pinoy traders.

Secondly, the old PSEGet version i have seems no longer working, hindi na po ata tugma sa new formatting ni PSE EOD. Now, I just found out that there is a new version, I've immediately tried to install it sa computer ko pero it seems like it's not working. Do you have a full guide Sir on how to install the new version?

Regards,
Alvin

**Comment by yeahbah** [comment]
https://www.youtube.com/watch?v=MmuXhr0nuK8
